### PR TITLE
Kmp view departments

### PR DESCRIPTION
**Pull request by kevinpenny3**
# Description
Created the Departments Controller and DepartmentsViewModel. I Get all departments, allow for editing of departments, and when viewing department details it will display a list of employees for that department.
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [x ] New feature (non-breaking change which adds functionality)
# Testing Instructions
- Click on Departments in the nav bar
- Check to see Departments Shows All Information (Name, Budget, Employee Count)
- Click Add Department and Enter a Name and Budget
- Save Department, Check to see if information was added to the list
- Click Details on a Department
- View details and see if the information is populated (Name, Budget, List of Employees)
# Checklist:
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings or errors
- [x ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jamesnitz — CHANGES_REQUESTED** [review]
1. Clicking details and then clicking edit does not populate fields. Fix in the details views page.

2. Details for newly created departments cause breaks

**Review by jamesnitz — APPROVED** [review]
looks good now

**Comment by wggreen** [comment]
Looks good to me

**Review by wggreen — APPROVED** [review]
Looks good (did it right this tine)

**Pull request merged**
